create table document (id bigint not null auto_increment, date_time date, description text, language integer not null, name varchar(255), title varchar(255), document_type_id bigint, primary key (id)) engine=InnoDB;
create table document_type (id bigint not null auto_increment, title varchar(255), primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, author varchar(255), content text, date_time date, description text, language integer not null, title varchar(255), primary key (id)) engine=InnoDB;
create table news_images (news_id bigint not null, images_id bigint not null) engine=InnoDB;
create table news_image (id bigint not null auto_increment, alt varchar(255), is_main bit not null, name varchar(255), news_id bigint, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table service (id bigint not null auto_increment, date_time date, description text, language integer not null, title varchar(255), primary key (id)) engine=InnoDB;
create table subscriber (id bigint not null auto_increment, date_time date, email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table suggestion (id bigint not null auto_increment, content text, date_time date, primary key (id)) engine=InnoDB;
create table tender (id bigint not null auto_increment, content text, date_time date, deadline date, description text, image varchar(255), language integer, title varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, full_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null, primary key (user_id, roles_id)) engine=InnoDB;
create table vacancy (id bigint not null auto_increment, content text, date_time date, deadline date, description text, image varchar(255), language integer, title varchar(255), primary key (id)) engine=InnoDB;
alter table news_images add constraint UK_8caof24wulbu7hhfuwlm1kq9u unique (images_id);
alter table document add constraint FKe2no7rafy2kby8devwkuyfak3 foreign key (document_type_id) references document_type (id);
alter table news_images add constraint FKs5qjykibp5q7s5vsr7cw8nfc9 foreign key (images_id) references news_image (id);
alter table news_images add constraint FKhcwu8kdkcw4mkqlygdq0g3dtq foreign key (news_id) references news (id);
alter table news_image add constraint FKhwajir19rbhvdif5as4g6wcwf foreign key (news_id) references news (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
